export const FETCH_PATIENT_REQUEST = 'FETCH_PATIENT_REQUEST';
export const FETCH_PATIENT_SUCCESS = 'FETCH_PATIENT_SUCCESS';
export const FETCH_PATIENT_FAILURE = 'FETCH_PATIENT_FAILURE';



export const POST_PATIENT_SUCCESS = 'POST_PATIENT_SUCCESS';
export const POST_PATIENT_FAILURE = 'POST_PATIENT_FAILURE';
